apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-client
  namespace: proyecto2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grpc-client
  template: # ¡Este campo debe estar al mismo nivel que 'selector' y 'replicas'!
    metadata:
      labels:
        app: grpc-client
    spec:
      containers:
        - name: grpc-client
          image: 18fernando/grpc-client:latest
          ports:
            - containerPort: 8081
          env:
            - name: GRPC_SERVER_RABBIT
              value: "grpc-server-kafka:50051"
            - name: GRPC_SERVER_KAFKA
              value: "grpc-server-rabbit:50052"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20

---
apiVersion: v1
kind: Service
metadata:
  name: grpc-client
  namespace: proyecto2
spec:
  selector:
    app: grpc-client
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP
