apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbit-consumer
  namespace: proyecto2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbit-consumer
  template:
    metadata:
      labels:
        app: rabbit-consumer
    spec:
      containers:
        - name: rabbit-consumer
          image: 18fernando/rabbit-consumer:1
          env:
            - name: RABBITMQ_URL
              value: "amqp://guest:guest@rabbitmq.rabbitmq.svc.cluster.local:5672/"
            - name: RABBITMQ_QUEUE
              value: "weather-queue"
