apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: grpc-client-hpa
  namespace: proyecto2
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: grpc-client
  minReplicas: 1
  maxReplicas: 5 # Puedes ajustar según necesidades
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60 # Escala cuando el uso promedio de CPU supere el 60%
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 70 # Escala cuando el uso promedio de memoria supere el 70%
