apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: grpc-server-kafka-hpa
  namespace: proyecto2
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: grpc-server-kafka
  minReplicas: 1
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: External
      external:
        metric:
          name: kafka_consumer_lag
          selector:
            matchLabels:
              topic: my-topic
              consumer_group: grpc-consumer
        target:
          type: AverageValue
          averageValue: 1000
