apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: grpc-server-rabbit-hpa
  namespace: proyecto2
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: grpc-server-rabbit
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
    - type: External
      external:
        metric:
          name: rabbitmq_queue_messages
          selector:
            matchLabels:
              queue: weather-queue
              vhost: "/"
        target:
          type: AverageValue
          averageValue: 100 # Escala cuando hay más de 500 mensajes en cola
